spring.application.name=teamflow-backend
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/teamflow_db
spring.datasource.username=postgres
spring.datasource.password=aashish@9970

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true